/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/

#ifndef __iotDefines_h__
#define __iotDefines_h__
    
typedef enum _iotKeys {
    IOT_BOARD_ID,
    IOT_TIMESTAMP,
    IOT_INDEX,
    IOT_TEG_ENABLED,
    IOT_TEG_STATE,
    IOT_TEG_INPUT_VOLTAGE,
    IOT_TEG_INPUT_CURRENT,
    IOT_TEG_INPUT_POWER,
    IOT_TEG_MIDDLE_VOLTAGE,
    IOT_TEG_MIDDLE_CURRENT,
    IOT_TEG_MIDDLE_POWER,
    IOT_TEG_OUTPUT_VOLTAGE,
    IOT_TEG_OUTPUT_CURRENT,
    IOT_TEG_OUTPUT_POWER,
    IOT_TEG_VOPEN,
    IOT_TEG_ISHORT,
    IOT_TEG_PWM_VALUE,  // 17
    IOT_SYS_TEMPERATURE_BASE = 20,  // 3 thermocouple, 2 thermistor, 8 TMP100, 2 die temps, 2 fan controller temps = 17 total
    IOT_SYS_INPUT_FAN_SPEED = 40,
    IOT_SYS_OUTPUT_FAN_SPEED,
    IOT_SYS_PUMP_ON,
    IOT_SYS_DUMP_VALVE_OPEN,
    IOT_SYS_EMERGENCY_SHUTDOWN,
    IOT_SYS_FLOW_RATE,
    IOT_SYS_12V_POWERGOOD,
    IOT_SYS_ON_BATT,

    IOT_SYS_24V_VOLTAGE,
    IOT_SYS_24V_CURRENT,
    IOT_SYS_24V_POWER,
    IOT_SYS_LIION_VOLTAGE,
    IOT_SYS_LIION_CURRENT,
    IOT_SYS_LIION_POWER,
    IOT_SYS_LIION_ENABLE,
    IOT_SYS_LIION_POWERGOOD,
    IOT_SYS_LIION_STAT1,
    IOT_SYS_LIION_STAT2,
    IOT_SYS_LIION_STATE,
    IOT_SYS_LEAD1_VOLTAGE,
    IOT_SYS_LEAD1_CURRENT,
    IOT_SYS_LEAD1_POWER,
    IOT_SYS_LEAD1_DESULFATE,
    IOT_SYS_LEAD1_CAPACITY,
    IOT_SYS_LEAD1_ENABLE,
    IOT_SYS_LEAD1_POWERGOOD,
    IOT_SYS_LEAD1_STAT1,
    IOT_SYS_LEAD1_STAT2,
    IOT_SYS_LEAD1_STATE,
    IOT_SYS_LEAD2_VOLTAGE,
    IOT_SYS_LEAD2_CURRENT,
    IOT_SYS_LEAD2_POWER,
    IOT_SYS_LEAD2_DESULFATE,
    IOT_SYS_LEAD2_CAPACITY,
    IOT_SYS_LEAD2_ENABLE,
    IOT_SYS_LEAD2_POWERGOOD,
    IOT_SYS_LEAD2_STAT1,
    IOT_SYS_LEAD2_STAT2,
    IOT_SYS_LEAD2_STATE,
} iotKeys_t;
    
#endif // __iotDefines_h__

/* [] END OF FILE */
