# Enter your document number here (will also be the base of your filename)
DOCUMENT      =	mppt-teg

# Enter the filename of each of your EPS figures to create a dependancy on
# them
FIGURES       =	


#
# You should not need to edit anything below this line for proper operation
#

include Makefile.common

